mergeable:
  pull_requests:
    title:
      must_include:
        regex: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\(.+\))?!?: .+'
        message: 'PR title must follow Conventional Commits format (e.g., "feat: add feature")'
