# CI should only run on tags and pull requests for tags
name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # The announce job is used to plan the release and share that plan with other jobs.
  # It also handles creating the GitHub Release.
  announce:
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.plan.outputs.manifest }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install cargo-dist
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.21.1/cargo-dist-installer.sh | sh
      - id: plan
        run: |
          cargo dist plan --output-format=json > plan.json
          echo "manifest=$(cat plan.json | jq -c .)" >> $GITHUB_OUTPUT

  # The build job handles building the application for all requested targets.
  build:
    needs: announce
    strategy:
      matrix:
        # cargo-dist-version: 0.21.1
        target: [aarch64-apple-darwin, x86_64-apple-darwin]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install cargo-dist
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.21.1/cargo-dist-installer.sh | sh
      - name: Build
        run: cargo dist build --target=${{ matrix.target }} --output-format=json > dist-manifest.json
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.target }}
          path: |
            target/dist/*
            dist-manifest.json

  # The publish job handles final processing and uploading the built artifacts to the GitHub Release.
  publish:
    needs: [announce, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-dist
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.21.1/cargo-dist-installer.sh | sh
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          path: target/artifacts
          merge-multiple: true
      - name: Publish
        run: cargo dist publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
